version: '3.3'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=WoodenFurnitureStore
      - MYSQL_ROOT_PASSWORD=Thanhliem2612.
    ports:
      - '3307:3306'
    expose:
      - 3306
  be-nodejs:
    build:
      context: ../BE
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEV_DB_HOST=database-mysql
      - DEV_DB_PORT=3306
      - DEV_DB_NAME=WoodenFurnitureStore
      - URL_FE_CORS=http://localhost
    depends_on:
      - database-mysql
    ports:
      - 8080:8080
    expose:
      - 8080
  web:
    build:
      context: ../FE
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'
    depends_on:
      - be-nodejs


#docker-compose -p wooden_app up -d